### ISSUE TITLE
Jobs getting stuck at preparing build

### ISSUE THREAD

**Issue by pn-santos** [concourse/concourse#2010]
# Bug Report

For the last couple of days we've been having a strange issue. Sporadically Concourse seems to be getting stuck at the "preparing build" step, all the pre-requisitives show a ✔️ next to them (so nothing is actually pending as far as we can see) however the job stays stuck forever in that state. 

When this starts happening, it affects all jobs in all teams. Fly watch of the pending jobs also hangs and shows no output. I haven't been able to narrow down exactly what fixes it, one time it was retiring+reseting one of the workers. Another time that wasn't enough and I had to delete+recreate the pipeline with the stuck job.

The only error messages I could see in the logs were these (logged when one of the workers was reset):
```
{"timestamp":"1517591651.263898134","source":"atc","message":"atc.create-job-build.trigger-immediately.try-start-next-pending-build.scan.failed-to-create-container-in-db","log_level":2,"data":{"build-id":8663,"build-name":"70","error":"pq: insert or update on table \"worker_resource_config_check_sessions\" violates foreign key constraint \"worker_resource_config_check__resource_config_check_sessio_fkey\"","input":"npm-debian-image","job_name":"test-mailer-master","resource":"npm-debian-image","session":"48972.1.1.2"}}
{"timestamp":"1517591651.263942957","source":"atc","message":"atc.create-job-build.trigger-immediately.try-start-next-pending-build.scan.failed-to-initialize-new-container","log_level":2,"data":{"build-id":8663,"build-name":"70","error":"pq: insert or update on table \"worker_resource_config_check_sessions\" violates foreign key constraint \"worker_resource_config_check__resource_config_check_sessio_fkey\"","input":"npm-debian-image","job_name":"test-mailer-master","resource":"npm-debian-image","session":"48972.1.1.2"}}
{"timestamp":"1517591651.265183210","source":"atc","message":"atc.create-job-build.trigger-immediately.failed-to-start-next-pending-build-for-job","log_level":2,"data":{"error":"pq: insert or update on table \"worker_resource_config_check_sessions\" violates foreign key constraint \"worker_resource_config_check__resource_config_check_sessio_fkey\"","job-name":"test-mailer-master","job_name":"test-mailer-master","session":"48972.1"}}
```
(the above was printed for multiple jobs, above are just the logs for one of the jobs)

We also see the messages below quite frequently on a regular basis (but since they also show up when everything is running normally I'm not sure they are relevant):
```
{"timestamp":"1518004152.986703157","source":"atc","message":"atc.volume-collector.run.orphaned-volumes.mark-created-as-destroying.failed-to-transition","log_level":2,"data":{"error":"volume cannot be destroyed as children are present","session":"62.13706.1.43","volume":"69b59425-83cd-4511-4a7f-f0a011c0b697","worker":"ccn4"}}
```

The following can also be handy:

* Concourse version: 3.8.0
* Deployment type: binary
* Infrastructure/IaaS: Running on VMs (Debian 8.10 OS with 4.9.0-0.bpo.3-amd64 kernel)

**Comment by brownjohnf** [comment]
I believe we're also experiencing this, but on concourse 3.10.0.

**Comment by debtcollapse** [comment]
I can confirm this is happening on 3.11.0 as well.

**Comment by pn-santos** [comment]
We just had this happen again with 3.12 still... not sure if it can be a clue or it's just a fly issue but after aborting a pending build this is was fly showed when listing builds:
```
6      aborted    n/a                       2018-04-30@10:44:04+0100  423633h44m4s
```
(this is the build that was stuck in pending state) the duration is very strange as it was pending for less than 10min until I aborted it...

**Comment by dpb587** [comment]
Also been seeing this for a while, including on 3.13.0. I'm only noticing it happen on resources which are shared across many pipelines (e.g. 15+ pipelines). I assume it's some sort of scheduling race, as I've noticed it when 1) concourse is restarted, and 2) occasionally when a new pipeline is created. It does seem to resolve itself eventually, but when the check interval is longer, that can take a while and this is more noticeable.

**Comment by pn-santos** [comment]
I can confirm that the cause seems to be what @dpb587 suggested. We have several resources shared (i.e. with the exact same configs) across multiple pipelines, and whenever this happens, the jobs in question (stuck with pending) have at least one of those shared resources as input.

Also I tried doing a check-resource on those resources and there is always at least one where the `cr` fly command just hangs, never returning a response.

A restart of the ATC seems to fix the issue and all stuck jobs will resume their builds.

The resource where I've been able to confirm this behavior are git resource.

**Comment by akamalov** [comment]
Concourse 3.14.0 and having the same issue

**Comment by colmtuohy** [comment]
Can confirm we also see this on 3.13.0 also, making the system unusable. Downgrading again to 3.9.2 as a result, as it did not seem as bad then. 3 atcs, 18 workers

**Comment by ralekseenkov** [comment]
3.14.1

pipeline stuck at pending state

resource shows
- pq: insert or update on table "worker_resource_config_check_sessions" violates foreign key constraint "worker_resource_config_check__resource_config_check_sessio_fkey"

**Comment by akamalov** [comment]
I just had one yesterday. I immediately re-ran the job and it went through. I think it has something to do with job locking or some sort.

**Comment by vito** [comment]
I found a theoretical cause for this, mentioned in https://github.com/concourse/concourse/issues/2454 (under point 1). I think we could fix it by moving the find-or-create of the resource config into the lock acquisition loop.

Theoretically this should only happen for manually-triggered builds. So there may be some other cause. I'm kind of hoping a lot of this just gets cleaned up as part of https://github.com/concourse/concourse/issues/2386.

**Comment by vito** [comment]
Next time someone runs into this could you take a stack dump?: https://github.com/concourse/concourse/wiki/Troubleshooting#taking-a-stack-dump

**Comment by munju** [comment]
I happened again... here is the dump:
[dump.txt](https://github.com/concourse/concourse/files/2332417/dump.txt)

**Comment by pn-santos** [comment]
@vito @munju (a colleague of mine) didn't say but the dump he posted was from 3.14.1 binary concourse deployment (not sure if that info is of interest)

**Comment by lrstanley** [comment]
We've run into the same issue, I believe.

Hung at `checking job is not paused`/`preparing build` stage. This is the first time it's happened to us, and it was right after we had a major git outage, which caused all of our git resources to be unusable for hours. 3-4 git resources per pipeline, over 400 pipelines.. after git came back online, now we're starting to see these issues.

Worth noting that we also get the `pq: insert or update on table [...]` error when our git resources get backed up due to downed external services, but I believe this was resolved in another issue/commit. We also see `volume cannot be destroyed as children are present [...]` frequently much like the original issue.

Restarting atc/tsa doesn't seem to make any difference, still hung for us. recreating the pipeline doesn't make a difference. Aborting and starting the run over again doesn't make a difference either.

Concourse v3.13.0, bosh deployed

Though, I believe there may be some relation in my case to https://github.com/concourse/concourse/issues/520 -- even though in our example, we only have one job in the given pipeline.

I was able to resolve the issue by unpausing.. an unpaused pipeline, hah. As you can see below, it's not paused, but I run the `unpause-job` subcommand anyway, and it no longer had any issue.

```console
$ fly -t env-my-team -p my-pipeline
name               paused  status  next
my-pipeline-job    no      n/a     n/a
```

```console
$ fly -t env-my-team unpause-job -j my-pipeline/my-pipeline-job
unpaused 'my-pipeline-job'
```

**Comment by clarafu** [comment]
This issue was fixed along with #1598, with the fix being to remove the worker resource config check sessions table and merge it with the resource config check sessions table. If you want to read more on the fix you can do so here [commit](https://github.com/concourse/concourse/commit/7fccfb4c1e802f141147724386ca58edaaca2dac). Another issue was found which was related is #2911 where the resource configs were being gced before they were used. This issue was fixed with a commit that creates and uses the resource configs within one transaction.

**Comment by evanchaoli** [comment]
When this fix will be released?

**Comment by vito** [comment]
@evanchaoli 5.0

**Comment by tanner-bruce** [comment]
@vito @clarafu I am still seeing this in v5

```
concourse-concursed-web-7c9b746fb4-r7xs4 concourse-concursed-web {"timestamp":"2019-04-23T19:01:16.919870803Z","level":"error","source":"atc","message":"atc.collector.tick.volume-collector.mark-volumes.mark-created-as-destroying.failed-to-transition","data":{"error":"volume cannot be destroyed as children are present","session":"23.137.9.2.4","volume":"69fa08a3-c97e-49ef-5d33-884b6f823a57","worker":"concourse-concursed-worker-2"}}
```

Here is my stackdump: https://gist.github.com/tanner-bruce/e410118ea9710bd9670f9e920221b27d

**Comment by vlad-ro** [comment]
Seeing this as well:
```json
{
    "timestamp": "2019-04-29T12:56:17.482867576Z",
    "level": "error",
    "source": "atc",
    "message": "atc.collector.tick.volume-collector.mark-volumes.mark-created-as-destroying.failed-to-transition",
    "data": {
        "error": "volume cannot be destroyed as children are present",
        "session": "21.30613.10.2.2",
        "volume": "fec219c8-9380-4d34-67d9-55989151e322",
        "worker": "0b2dc3e69de8"
    }
}
```

**Comment by vito** [comment]
@tanner-bruce @vlad-ro That log line is a red herring: https://github.com/concourse/concourse/issues/1780

**Comment by DanielJonesEB** [comment]
I'm seeing this in 5.1.0, both BOSH-deployed with Control Tower and via the Helm chart with a customer.

I've had one build sat pending for 40 minutes now:
<img width="346" alt="Screenshot 2019-05-18 at 08 10 19" src="https://user-images.githubusercontent.com/11817552/57966024-6756f580-7944-11e9-8b53-cd364cc6e02e.png">


```terminal
$ fleb workers
name                                  containers  platform  tags  team  state    version
c228046e-4e80-4ceb-b786-757fd16c2d27  81          linux     none  none  running  2.1
c3038858-62e7-4153-a135-975e6eb7c6e7  106         linux     none  none  running  2.1
```

All bar 8 of the containers are check containers. Web node (AWS t2.large) seems happy: `load average: 0.53, 0.52, 0.55`. `concourse` process is spiking up to about 61% CPU. 39 pipelines, a couple of teams, but only one with any pipelines.

I can't see anything obviously wrong in the logs. Any suggestions of what to look for?

**Comment by tanner-bruce** [comment]
@vito that log line may be a red herring for sure however I am having the same symptoms as this issue states.

- my builds are getting stuck with full check marks
- restarting ATC's gets them going again
- logs are full of red herring line

The stack dump I provided is of a cluster stuck in this state. Should I open a new ticket describing what is happening?

**Comment by DanielJonesEB** [comment]
Happening again on a different pipeline that I'm trying to iterate on. Build was pending for about seven hours. Aborting the build through the UI doesn't work, but `fly abort-build` seems to be reflected in the UI after some time.

Something that did help:
* restart web VM
* abort build in UI
* no change in UI
* come back to this tab to say restarting VM didn't help
* a few minutes later notice the build was aborted (turned brown in the UI, had "loading" for build details)
* triggered through the UI, and it scheduled normally

**Comment by vito** [comment]
@tanner-bruce Yeah, please open new issues with stack dumps - comments on closed issues (especially issues like this which are very broadly defined but had a specific resolution) are hard to keep track of and prioritise.

FWIW #3928 may help but I can't really confirm whether it's the root cause for the hanging in your case.

**Comment by u2g-tg** [comment]
I just received these symptoms with 5.1.0, after a manual trigger, then resolving an absent lock for the pool resource. All build pre-steps were ticked, but it didn't transition out of pending. 

A restart of the web node caused the job to start working without having to abort it.

**Comment by yermulnik** [comment]
Unpausing unpuased stuck in pending state job helped me as per this post https://github.com/concourse/concourse/issues/2010#issuecomment-419434832
