### ISSUE TITLE
Volumes expiring ahead of container (not being heartbeated?)

### ISSUE THREAD

**Issue by vito** [concourse/concourse#373]
This causes e.g. `fly hijack` to bail as looking up the container works. It might work fine for the duration of the build, but when the build finishes we may release the volumes with a shorter TTL than necessary (e.g. if build fails they should all be released for 1h).

```
atc.hijack.hijack.volume.volume-is-missing-on-worker: volume mounted to container is missing
```

**Comment by MatthiasWinzeler** [comment]
We're facing this error `volume mounted to container is missing` as well. Not when using `fly hijack`, but randomly on some jobs that were working before - when I trigger the build of these jobs manually, they always fail. Example:

```
fly -t tutorial trigger-job -j "boshreleases/create boshrelease"
..

started 'boshreleases/create boshrelease'

fly -t tutorial watch -j "boshreleases/create dr9000-boshrelease"
...

volume mounted to container is missing
errored
```

We have a setup with 1 web VMs and 3 worker VMs. Even after recreating the workers, the error still persists. I encountered it before and solved it by deleting the pipeline and creating it again - but this is not a durable solution since we need the build history. 

Can we somehow investigate further? Are there some interesting logs, can we investigate Garden, ...?

**Comment by freelock** [comment]
I'm experiencing this issue frequently as well... Or at least I'm getting this error message.

For example, this job failed previously (a "correct" failure in that the task failed during execution). I pushed a change to the script in the "pipelines" resource and manually re-triggered the job and got this:

![selection_218](https://cloud.githubusercontent.com/assets/46937/15882231/8ed1be1c-2cf1-11e6-854b-5830b3b50b06.png)

**Comment by freelock** [comment]
Restarting my untagged worker does seem to make this work again...

**Comment by cunnie** [comment]
Thanks @MatthiasWinzeler — that fix (`delete from containers where pipeline_id = 113;`) worked for me!

**Comment by kirederik** [comment]
We're still seeing this error when we trigger a job that uses a custom resource with latest (1.4.1) concourse (running on a bosh-lite deployed to aws). We have two workers (one tagged) and get the same error in both of them.

ATC logs:

```
{"timestamp":"1468235584.154454947","source":"atc","message":"atc.create-job-build.trigger-immediately.scheduling.do.put.init-with-sources.failed-to-find-volume-in-db","log_level":2,"data":{"build-id":209,"build-name":"7","error":"volume mounted to container is missing","job":"my-job,"name":"custom-resource","session":"1028923.1.1.6.1.2"}}
{"timestamp":"1468235584.214034081","source":"atc","message":"atc.create-job-build.trigger-immediately.scheduling.do.put.init-with-sources.failed-to-create-volume","log_level":2,"data":{"build-id":209,"build-name":"7","error":"unexpected response code of: 500","job":"my-job","name":"custom-resource","session":"1028923.1.1.6.1.2"}}
```

Baggageclaim logs:

```
{"timestamp":"1468234689.202074766","source":"baggageclaim","message":"baggageclaim.repository.create-volume.failed-to-materialize-strategy","log_level":2,"data":{"error":"exit status 1","handle":"3ca855aa-85de-41d1-4251-d3065e1cc4e9","session":"3.4548654"}}
```

We tried the fix suggested by @MatthiasWinzeler without luck. 
If we specify the custom resource in the `resource_types` section of the pipeline configuration, the job runs without any problem.
