### ISSUE TITLE
Allow disabling `check_every` entirely for resources

### ISSUE THREAD

**Issue by joshuajabbour** [concourse/concourse#575]
It would be helpful to be able to disable automatic resource checking entirely. Use case is webhooks, where you want the resource check to be manually initiated only.

Webhook-like functionality (that don't require auth) can be achieved currently by posting to `/api/v1/pipelines/:pipeline_name/resources/:resource_name/check`, but you still have to set `check_every` to some value ([just not `0`](https://github.com/concourse/concourse/issues/572)!). Current practice is to use a very large interval, but disabling would be more correct for this use case.

Related to https://github.com/concourse/concourse/issues/331, but not dependent on that issue (though that issue will likely want this feature included).

**Comment by chendrix** [comment]
Provided by concourse/atc#163

**Comment by dingxiangfei2009** [comment]
@chendrix Not exactly. `check_every` is always enforced, regardless of the `webhook_token` value.

**Comment by eedwards-sk** [comment]
@chendrix can we re-open this?

I agree I would like to be able to disable `check_every` resource checking. Not just for webhooks but for instances where I only ever expect to run pipelines manually (no triggers).

**Comment by vito** [comment]
I'll reopen since it does seem like it was closed mistakenly as the PR doesn't actually resolve this.

I still think setting the interval to a high value is better than disabling it outright, since webhook events can be missed. But if folks feel strongly enough to PR it I'm happy to review. 👍

**Comment by xdom** [comment]
My use-case is to only have `put` command (for deploying environments via Helm). Why does it even schedule checks when I don't have any `get` commands?

**Comment by eedwards-sk** [comment]
This is still something I'm actively interested in. I tried using extremely high check intervals but ran into some edge cases where the resource would never end up checking itself (even during manually initiated runs) and could only be fixed with a manual check of the resource or by re-creating the web node.

Until global resources are completely ironed out, being able to disable automatically checking a resource would be very useful for keeping resource usage low on small workers with lots of resources that don't often change.

**Comment by robwhitby** [comment]
+1 from me. I've just been investigating why we have such high load in web and db when idling. It seems a lot of it is due to resource checks for resources that don't even have versions because they are "out only" - e.g. slack notifications or deployments

**Comment by eedwards-sk** [comment]
Keep Open - I'm still seeing weird behavior when using high `check_every` values which is only a workaround due to not having this feature.

**Comment by vito** [comment]
FWIW - high check intervals should behave better with LIDAR (https://github.com/concourse/concourse/issues/3788) - as it should resolve this issue: https://github.com/concourse/concourse/issues/3678

LIDAR will be available (off by default) in v5.6.

@robwhitby re: the redundant checking due to notification-style resources, that should be resolved once we introduce 'notification prototypes' - then they won't be a resource at all and thus won't have any `check`s to perform in the first place. Some early thoughts on that here: https://github.com/concourse/rfcs/pull/37#discussion_r327724084 (on the 'prototypes' RFC)

@xdom Yeah, this is an optimization I've thought about before (don't perform `check`s for resources that don't have any `get`s in the first place). There might be other complications to these semantics (as tends to happen with optimizations) but it at least sounds intuitive. There's also a chance that resources shouldn't be used for this use case anyway in favor of some other prototype-based interface.

---

All this is to say I still wouldn't mind a flag for this, but we're focusing on the long-term fixes ourselves, hence why this hasn't been prioritized. :slightly_smiling_face: Maybe we add a flag for now and phase it out once the things people use it for gradually transition to something other than a resource.

**Comment by evanchaoli** [comment]
I'm thinking even further. I want to propose a new type of resource "put-only". 

* For "put-only" resource, `check` is disabled, so that one container is saved. Most of pipelines have `put-only` resources, by disabling `check`, a lot of containers are avoided, thus save a lot of worker resources.
* One more thing with "put-only" resource, `out` script should also get a `destDir` where it can generate some artifacts like `in` does. The use case is, some `put` generates some files, but `put` have no way to generate artifacts, only `get` can. So that `put` has to pass generated files to `get`, but there is no a good way to pass file from `put` to implied `get`. Only way I see is to embed file content into version, and version is passed to implied `get`. This way works, but it shows a long random string as version on GUI, which looks ugly.
 
@vito WDYT?

**Comment by vito** [comment]
@evanchaoli I would argue that `put`-only resources aren't resources at all, and are instead trying to be used as a task, only with a better interface for configuration (tasks only really have env vars).

Have a look at concourse/rfcs#37 - it's a proposal for a new concept that should help with your use case. It will be used as the new building block for 'resources' (described in concourse/rfcs#38) while also being able to be used for arbitrary actions and new interfaces in the future.

**Comment by evanchaoli** [comment]
@vito Good to read those RFCs, I believe that's the correct direction to go. However I'm afraid that doesn't fully solve my problem. Let me give a specific use case example.

We have a change log generator resource type. Its `put` take a `git` resource and generates change log of the `git` resource. Generated change log file needs to be passed to following steps. Since only `get` may generate output artifacts, we can only encode change log content into a string and pass the long string as version to implied `get`.

Conceptually, a resource after `get` holds a version of the resource within a job context. A `put` generates a version, and implied `get` refreshes local copy of the new version, so that following step may consume fresh resource. The problem here is, Concourse assumes all resources are remote, `put` generates a new version and push to remote, then implied `get` fetches the new version back to local. From this perspective, if `put` directly refresh local copy of the new version, then implied `get` can be avoided. One problem is, which may cause `put` and `get` to contain duplicate logic of refresh local copy of a version. But technically, reusing code should not be an issue to programmers.

Or reflecting to the RFC, maybe add a new method `put_and_get`, and make `check` also optional. So that some resource can be local only within a job.

**Comment by vito** [comment]
@evanchaoli There's no need for a `put_and_get`. :slightly_smiling_face: The 'prototypes' RFC leaves it up to the prototype author to define their own messages, and any message can take inputs and produce outputs. In your case you could implement a prototype which supports a message called whatever you like - say, `generate-changelog`.

Resources are just prototypes which support a particular set of messages: `check`, `get`, `put`, and `delete`.

(This is getting a bit off-topic btw.)

**Comment by evanchaoli** [comment]
@vito Cool! Let me wait for the "prototype" feature.

**Comment by eedwards-sk** [comment]
stalebot, bad!

**Comment by willhughes-au** [comment]
3.5 years on, any chance this might get some attention?

**Comment by varnem2** [comment]
Bump.

I have a perfect use case for this where a number of solutions are acceptable. I have an external password vault that emits a webhook upon a password change event. When that password change event occurs, I would need to be able to kick off my password to deploy the new password. Today, with Concourse I can trigger a refresh on a resource, but if I use my source code then it doesn't start my job because my source code hasn't changed.

**Comment by adityapahuja** [comment]
Terraform resource (https://github.com/ljfranklin/terraform-resource) keeps assuming a role every one minute in AWS if its backend_type is set to s3 and backend_config.role_arn is specified. Could we have an option to disable `check_every` please.

**Comment by vito** [comment]
Converting this into a Discussion per the [new framing of Issues vs Discussions](https://blog.concourse-ci.org/nobody-wants-a-stale-bot/).

As mentioned in https://github.com/concourse/concourse/issues/575#issuecomment-534757273, LIDAR should resolve issues with long `check_every` values, so that workaround should work a lot better now.

In v6.0.0, an optimization was added so that resources which are never used in `get` steps will not be checked at all. This should significantly lower checking for `put`-only resources such as notifications and deployments. (Notifications will be further addressed by concourse/rfcs#28.)

In v6.1.0, a `--resource-with-webhook-checking-interval` flag was added so that a higher default value may be specified for resources configured with a webhook.

I'm chewing on an idea for a better way to support webhooks that won't require configuring URLs and per-resource callbacks. Once I have something more concrete I'll give an update on this issue.

@willhughes-au Broadly speaking, "disabling checking" is not a feature we want to support because it tends to indicate a misuse of the resource interface. [This blog post](https://blog.concourse-ci.org/reinventing-resource-types/) covers this topic in depth. If this feature is ever implemented, it will be by the community, and it will fall under scrutiny as to whether it's really necessary.

@varnem2 Interesting! You may want to follow https://github.com/concourse/rfcs/pull/27 - I think that more precisely targets your use case.

@adityapahuja Do any of the above mitigations help? If not, can you describe how you're using the resource type?
