### ISSUE TITLE
If containerd socket is interrupted, worker is stuck in limbo

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#6752]
## Summary

Under some circumstances, the containerd backend fails to connect to the running containerd.

Instead of failing with an error code and to be restarted externally, the concourse worker is stuck in limbo

## Steps to reproduce

```
Mär 26 11:24:46 jurassicpark concourse[116917]: 7.0.0
Mär 26 11:24:46 jurassicpark systemd[1]: Started concourse worker cantaloupe.
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.208664495Z","level":"info","source":"baggageclaim","message":"baggageclaim.using-driver","data":{"driver":"btrfs"}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210227121Z","level":"info","source":"baggageclaim","message":"baggageclaim.listening","data":{"addr":"127.0.0.1:7788"}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210676237Z","level":"error","source":"worker","message":"worker.garden-runner.logging-runner-exited","data":{"error":"Exit trace for group:\ncontainerd-garden-backend exited with error: client init: failed to connect to addr /run/containerd/containerd.sock: failed to dial \"/run/containerd/containerd.sock\": connection error: desc = \"transport: error while dialing: dial unix /run/containerd/containerd.sock: connect: connection refused\"\ncontainerd exited with error: signal: interrupt\n","session":"8"}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210835173Z","level":"info","source":"worker","message":"worker.debug-runner.logging-runner-exited","data":{"session":"10"}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210866845Z","level":"info","source":"worker","message":"worker.baggageclaim-runner.logging-runner-exited","data":{"session":"9"}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210817072Z","level":"info","source":"worker","message":"worker.container-sweeper.sweep-cancelled-by-signal","data":{"session":"6","signal":2}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210916679Z","level":"info","source":"worker","message":"worker.container-sweeper.logging-runner-exited","data":{"session":"13"}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210847092Z","level":"info","source":"worker","message":"worker.volume-sweeper.sweep-cancelled-by-signal","data":{"session":"7","signal":2}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210946690Z","level":"info","source":"worker","message":"worker.volume-sweeper.logging-runner-exited","data":{"session":"14"}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.210887724Z","level":"info","source":"worker","message":"worker.healthcheck-runner.logging-runner-exited","data":{"session":"11"}}
Mär 26 11:24:46 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:46.375937797Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}
Mär 26 11:24:47 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:47.376199722Z","level":"info","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.retrying","data":{"addr":"127.0.0.1:7777","network":"tcp","session":"4.1.4"}}
Mär 26 11:24:47 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:24:47.376582102Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}
```

followed by hours of:

```
Mär 26 11:26:00 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:26:00.416496417Z","level":"info","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.retrying","data":{"addr":"127.0.0.1:7777","network":"tcp","session":"4.1.4"}}
Mär 26 11:26:00 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:26:00.416904313Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}
Mär 26 11:26:01 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:26:01.417183319Z","level":"info","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.retrying","data":{"addr":"127.0.0.1:7777","network":"tcp","session":"4.1.4"}}
Mär 26 11:26:01 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:26:01.417529830Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}
Mär 26 11:26:02 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:26:02.417711254Z","level":"info","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.retrying","data":{"addr":"127.0.0.1:7777","network":"tcp","session":"4.1.4"}}
Mär 26 11:26:02 jurassicpark concourse[116929]: {"timestamp":"2021-03-26T10:26:02.418090775Z","level":"error","source":"worker","message":"worker.beacon-runner.beacon.forward-conn.failed-to-dial","data":{"addr":"127.0.0.1:7777","error":"dial tcp 127.0.0.1:7777: connect: connection refused","network":"tcp","session":"4.1.4"}}
```

## Expected results

Fail with non zero exit code

## Actual results

Stuck in limbo, unresponsive.

## Triaging info

* Concourse version: 7.0.0  / 7.1.0
* Browser (if applicable): firefox
* Did this used to work? with gdn yes, with containerd for the most part

**Comment by mkocus** [comment]
Got similar/exact issue as you described.

In certain circumstances, only when running worker on containerd, the worker starts to become stalled. Basically after it happens the worker begings to bash the ATC several times a second indefinitely.
Logs indicated that:
**Worker**
```
{
  "timestamp": "2021-04-29T14:53:41.217233950Z",
  "level": "info",
  "source": "worker",
  "message": "worker.beacon-runner.beacon.forward-conn.retrying",
  "data": {
    "addr": "127.0.0.1:7788",
    "network": "tcp",
    "session": "4.1.15"
  }
}
{
  "timestamp": "2021-04-29T14:49:23.935291725Z",
  "level": "error",
  "source": "worker",
  "message": "worker.beacon-runner.beacon.forward-conn.failed-to-dial",
  "data": {
    "addr": "127.0.0.1:7777",
    "error": "dial tcp 127.0.0.1:7777: connect: connection refused",
    "network": "tcp",
    "session": "4.1.16"
  }
}
```
**ATC**
```
{
  "timestamp": "2021-04-29T14:47:07.102453650Z",
  "level": "info",
  "source": "atc",
  "message": "atc.tracker.notify.run.check-step.running-worker.garden-connection.retry-hijackable-client.retrying",
  "data": {
    "build": "check",
    "build_id": 4241368,
    "error": "dial tcp 127.0.0.1:35799: connect: connection refused",
    "failed-attempts": 1340408,
    "pipeline": "xxx",
    "ran-for": "53m1.461469236s",
    "resource": "version-pr",
    "session": "23.423789.9.3.1.1.2",
    "step-name": "version-pr",
    "team": "main"
  }
}
```

We start the worker using docker-compose:
```
version: '3'

services:
  concourse-worker:
    restart: always
    image: concourse/concourse:7.2.0
    command: worker
    privileged: true                            # needed to be able to create docker in docker
    volumes: ["/opt/concourse/:/opt/concourse/"]
    environment:
      CONCOURSE_TSA_HOST: ci.n7mobile.com:2222
      CONCOURSE_TSA_PUBLIC_KEY: /opt/concourse/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /opt/concourse/worker_key
      CONCOURSE_RUNTIME: containerd
      CONCOURSE_CONTAINERD_DNS_SERVER: 8.8.8.8  # needed because of https://github.com/concourse/concourse/issues/6544 and https://github.com/concourse/concourse/issues/6556

```

It didn't happen prior changing runtime to containerd when we deployed 7.2.0.

**Comment by waweber** [comment]
This happens to me as well. It happens reliably after the machine reboots, and, interestingly, it is not resolved by restarting the worker container. The only way I can fix it is to remove and recreate the container.

**Comment by waweber** [comment]
Alright, I spent a little time investigating and might have some useful information. If you want to reproduce this issue, follow along with me:

1. Create and start a worker container
2. Enter (`docker exec`) into the container, find the PID for containerd and ungracefully terminate it (`kill -9 <pid>`)
3. Exit the container and restart it
4. Check the logs and observe that it is repeatedly failing to connect like in this issue
5. Re-enter the container, and remove the /run/containerd/containerd.sock socket file
6. Exit the container and restart it
7. Observe that the worker runs normally

It looks like the issue stems from the socket file not being removed if containerd exits uncleanly. A temporary workaround is to mount a tmpfs at /run/containerd, so an old socket will be gone if the container restarts.

I'm not familiar with concourse's internals, but I imagine a few possibilities:

- Does containerd fail to run if its socket already exists?
- Is concourse waiting for the socket file to appear? Does it assume containerd has started in this case, even if it exited with an error?
- If containerd exits, does Concourse try to re-spawn it? Maybe concourse should exit?

**Comment by muntac** [comment]
@aoldershaw and I noticed that there are two different things happening here.

**Ifrit processes**

We use a package called [Ifrit](github.com/tedsuo/ifrit) to bring up all our process on the worker. This includes containerd binary, the garden server, beacon (which reaches out to the ATC and registers the worker), and baggageclaim.

**containerd takes longer to come up sometimes**

Ifrit tries to bring up all these in [parallel](https://github.com/concourse/concourse/blob/b17deca35f4d5aa48c215b149e13581485400a1b/worker/workercmd/worker.go#L213). But containerd is supposed to come up in [order](https://github.com/concourse/concourse/blob/b17deca35f4d5aa48c215b149e13581485400a1b/worker/workercmd/containerd.go#L207) before the Garden server. However, we don't actually wait for the containerd server to come up and when it takes slightly longer (as seems to when a socket file already exists) the Garden server process thinks it has failed, then itself exits causing Ifrit to asks all other processes to stop as well.

**All Ifrit process exit except beacon**

So the expected behaviour would be that all the Ifrit processes exit and the worker exits as well. But currently the beacon [registerWorker](https://github.com/concourse/concourse/blob/b17deca35f4d5aa48c215b149e13581485400a1b/worker/beacon.go#L60) method does not catch this signal nor does it react to context being [cancelled](https://github.com/concourse/concourse/blob/b17deca35f4d5aa48c215b149e13581485400a1b/tsa/client.go#L494). This is why in the original error logs OP was seeing worker ping the ATC for hours since beacon kept trying to register.


**Solution**
We have to fix both things:
1. Wait for containerd to come up by trying to ping it
2. Quit beacon when terminate signal is received or context is done
