### ISSUE TITLE
ATC and Workers stop executing jobs

### ISSUE THREAD

**Issue by freelock** [concourse/concourse#707]
# Bug Report

ATC and Workers often stop responding while running pipelines.

Environment:
- ATC - "hector"
- Untagged worker - "worker07" - on same subnet, 370GB SSD
- Tagged worker - "freelock06" - on different LAN, all jobs/resources are tagged

Symptoms:

After fully restarting everything, the system works great for 1 - 5 days. Then at some point things stop working.

Often the untagged worker is under very high load -- 30 - 40 seems usual, have seen > 60.

When it fails, the earliest thing I notice is jobs staying in the 'Pending' state, and fly workers shows only the tagged worker -- the untagged worker is gone from the list. The load on the untagged worker goes back to normal. The host is fully reachable, the worker process is running, but the ATC reports:

Oct 18 15:36:48 hector.freelock.com concourse[2675]: {"timestamp":"1476830208.490800619","source":"atc","message":"a
tc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"worker07"}}

After restarting the worker process, the web interface and fly appear to be fully functional, I can see jobs, containers, hijack, workers, etc. However nothing actually executes.

The load on the ATC never goes very high -- however one tell-tale sign in our monitoring system is the number of TCP connections on the ATC suddenly shoots up to a high number (430 right now, have seen 600 - 700) and just stays there, mostly unchanging, until I restart it.

I've been able to continue by restarting the ATC and then the workers. 

What more info can I provide to get to the bottom of this? It does appear to be happening more often than it did around 2.0.0 (but maybe we're just using it more).
## Environment:
- Concourse version: 2.2.1 (also earlier)
- Deployment type (BOSH/Docker/binary): Binary
- Browser (if applicable): N/A

**Comment by vito** [comment]
Do you know if restarting the workers is necessary, or does just restarting the ATC also work?

When the load average is high, can you hop on the worker and see what exactly it's doing? Maybe it's blocking on a bunch of disk I/O? Does it do this with no jobs running?

**Comment by charlieoleary** [comment]
Experiencing the same / similar issue.  Occasionally a worker will just fall out of the pool.  The service is still running and seems healthy, but ATC is reporting that it cannot find the worker.  ATC is scheduling other tasks.

```Oct 18 22:08:00 ip-10-0-18-196 concourse[5028]: {"timestamp":"1476828480.848477602","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-106-74"}}
Oct 18 22:08:00 ip-10-0-18-196 concourse[5028]: {"timestamp":"1476828480.884210110","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-106-74"}}
Oct 18 22:08:00 ip-10-0-18-196 concourse[5028]: {"timestamp":"1476828480.884296179","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-106-74"}}```

The worker is able to return by restarting it, and it will get new jobs, but the previous jobs will remain in limbo and never be rescheduled.  This can be resolved by restarting the ATC.

It's also worth noting that previous workers that were abandoned many days ago still complain about the worker no longer existing:

```Oct 18 23:48:28 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476834508.670708656","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-39-81"}}
Oct 18 23:48:28 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476834508.670747757","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-102-54"}}```

# Environment

* Concourse version: 2.3.1
* Deployment type (BOSH/Docker/binary): binary
* Browser (if applicable): Chrome

**Comment by charlieoleary** [comment]
@vito Just happened again, gathered the logs I had from before and after the worker went missing --

```
Oct 19 02:15:06 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843306.710886002","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:11 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843311.710939646","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:16 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843316.710894346","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:21 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843321.710833311","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:26 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843326.710859299","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:31 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843331.710858822","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:33 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843333.359785557","source":"tsa","message":"tsa.connection.forward-worker.heartbeat.start","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2.1.343","worker-address":"10.0.18.196:39097","worker-platform":"linux","worker-tags":""}}
Oct 19 02:15:33 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843333.361962080","source":"tsa","message":"tsa.connection.forward-worker.heartbeat.reached-worker","log_level":0,"data":{"remote":"10.0.163.8:59590","session":"2.1.343","took":"1.974756ms"}}
Oct 19 02:15:33 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843333.370611906","source":"tsa","message":"tsa.connection.forward-worker.heartbeat.done","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2.1.343","worker-address":"10.0.18.196:39097","worker-platform":"linux","worker-tags":""}}
Oct 19 02:15:36 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843336.710879326","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:41 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843341.710769892","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:46 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843346.710914612","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:15:51 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843351.710790157","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2","type":"keepalive"}}
Oct 19 02:16:03 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843363.370959759","source":"tsa","message":"tsa.connection.forward-worker.heartbeat.start","log_level":1,"data":{"remote":"10.0.163.8:59590","session":"2.1.344","worker-address":"10.0.18.196:39097","worker-platform":"linux","worker-tags":""}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.334625006","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"868b522c-7a7a-4e24-6a97-1bc8912ab537","pipeline-scoped-name":"<REDACTED>:resource:version","session":"13.1.12.503.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.345448256","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"1dafb740-ddc6-49fb-7eee-d020f3a176df","pipeline-scoped-name":"<REDACTED>:resource:version","session":"13.39.6.270.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.364311695","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"f0e5a338-451a-49ef-717a-4522106bbdeb","pipeline-scoped-name":"<REDACTED>:resource:slack","session":"13.35.5.330.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.366086245","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"e883dab7-6daf-41b7-575d-567de5097f14","pipeline-scoped-name":"<REDACTED>:resource:slack","session":"13.3.12.370.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.394351006","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"76c68a9e-a2ca-4bc9-439d-5da7e026aebf","pipeline-scoped-name":"<REDACTED>:resource:version","session":"13.7.7.499.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.422897339","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"b57eecaa-c328-45f7-419e-6b08425465f6","pipeline-scoped-name":"<REDACTED>:resource:slack","session":"13.29.8.463.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.424643517","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"ccfcbd00-c345-4953-5c0f-0c6428fe1d19","pipeline-scoped-name":"<REDACTED>:resource:version","session":"13.9.9.499.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.429136038","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"61363cb9-5dd8-4196-73fc-8027d15efb74","pipeline-scoped-name":"<REDACTED>:resource:version","session":"13.15.6.490.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.429246664","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"5e1f8fad-3006-4c7b-736c-8c26201ced65","pipeline-scoped-name":"<REDACTED>:resource:slack","session":"13.37.5.282.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.430464745","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"eae8c413-bd06-43a7-617b-d505adbb36ee","pipeline-scoped-name":"<REDACTED>:resource:slack","session":"13.47.5.270.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.432783127","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"4821899f-a643-41ef-774e-f079e65e826d","pipeline-scoped-name":"<REDACTED>:resource:slack","session":"13.15.5.496.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:47 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843407.930303574","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"a64923e1-0560-4c52-527a-4bb293049816","pipeline-scoped-name":"<REDACTED>:resource:<REDACTED>","session":"13.21.7.481.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:48 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843408.005168676","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"80a42678-014c-4d95-70c6-b6599460b7ac","pipeline-scoped-name":"<REDACTED>:resource:<REDACTED>","session":"13.11.7.478.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:50 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843410.083905935","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"e62e64d5-5e9b-44f5-5a37-c9096efe770c","pipeline-scoped-name":"<REDACTED>:resource:<REDACTED>","session":"13.13.7.484.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:50 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843410.386193514","source":"atc","message":"atc.syncer.<REDACTED>:radar.scan.tick.init.found-container-for-missing-worker","log_level":1,"data":{"container-handle":"cb66f259-bdbb-4a29-4d8b-6e0241fc22bd","pipeline-scoped-name":"<REDACTED>:resource:master","session":"13.31.4.484.1","worker-name":"ip-10-0-163-8"}}
Oct 19 02:16:58 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843418.690547943","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-163-8"}}
Oct 19 02:16:58 ip-10-0-18-196 concourse[21772]: {"timestamp":"1476843418.690579891","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-163-8"}}
```

Restarting the ATC alone was enough for the Worker to re-enter the pool, but all running jobs seem stuck.

**Comment by freelock** [comment]
@vito when the workers disappear, I need to restart them to get them to reappear. For the untagged worker, there's usually very high load when this happens -- I'll see if I can catch it next time before it disconnects to see what it appears to be doing.

When the ATC stops processing jobs, and both workers are showing in fly workers, restarting the ATC seems to work -- though the pending jobs don't appear to ever restart -- aborting those and triggering new builds of those jobs allow them to proceed.

I'm planning to update to 2.3.1 tonight/early tomorrow...

**Comment by ggeorgiev** [comment]
I was seeing this a lot with 2.2.1. I switched to 2.3.1 and haven't seen it after that.

**Comment by ggeorgiev** [comment]
actually, the issue is still there with 2.3.1, What I noticed though is that the frequency of workers going down increases when I am active developing pipelines (adding/removing/changing) and significantly goes down when there is no dynamics related to the pipelines. Hope this helps.

**Comment by ggeorgiev** [comment]
I switched to 2.4.0 - same thing. Can we prioritize this one? It is making the system almost unusable. Is this seen just from few?

**Comment by jinlee** [comment]
Seeing similar things on 2.4.0. How do I identify the bad worker? The `worker-id` on 2.4.0 seems to be a random hash.

```
{"timestamp":"1478251039.585185528","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"85995f28b409"}}
```

**Comment by w32blaster** [comment]
The same issue here on 2.4.0

**Comment by vito** [comment]
I'm starting to think this issue is worded a bit too broadly and that a lot of you are actually seeing different things. Namely, https://github.com/concourse/atc/issues/130 is something to check for if you've got pending jobs.

Workers disappearing under load would also be fixed by #629. Getting under such high load may also be addressed by #675.

**Comment by ggeorgiev** [comment]
It is hard to say (I am just a user), but at least for me none of those apply. There are no atc crash or workers overloads involved when the workers disappear.

I am starting to think it is related to loading docker images. I am having pipelines that build new images and use them in jobs letter on in the pipeline. I am having the feeling that workers disappear short after a new image is build and several following jobs try to load and cache it on the same worker.

**Comment by charlieoleary** [comment]
Though it hasn't happened in a couple of weeks now (*knock on wood*), none of this seemed to correlate to workers disappearing for me.  Our load per worker was always well within reason, there was plenty of CPU and memory, and there was nothing particularly out of the ordinary with what was going on in the system.  The workers would just disappear.  We thought it might be related to active development with the pipeline, but I was out for two days and it was still happening (I'm the only one currently doing active development on them).

**Comment by ggeorgiev** [comment]
You are lucky. I am seeing this 2-3 sometimes more times per day.

**Comment by vito** [comment]
A worker disappearing means it failed to heartbeat. This could be networking issues or a genuinely failing worker (resource contention, etc). Either way #629 should address that in some form (the worker will go to `standby` and we'll continue trying to reconnect to things that were running on it, and stop scheduling new work on it).

**Comment by charlieoleary** [comment]
In our particular case there were no apparent network issues (running binaries, three workers spread across three private subnets, ATC in public subnet).  The workers were still running when they disappeared from the ATC and restarting the ATC actually brought the worker back into the pool without needing to touch the worker at all.

**Comment by freelock** [comment]
@vito thanks for responding. I think we're definitely hitting #629. We also experience the behavior @charlieoleary describes in the previous comment -- which at least partially is in https://github.com/concourse/atc/issues/130 -- the most recent time this happened (yesterday) I did find a "too many files open" message in the logs, though that hasn't always been the case.

**Comment by charlieoleary** [comment]
Hrm, revising a bit. @vito, just had another worker drop out for the first time in awhile.  Investigated a bit and I do see high load on that specific worker around that time.  Fixed with an ATC restart, the worker itself was fine and left untouched.

**Comment by ggeorgiev** [comment]
It is the same for me. The worker is disconnected but seems fully operational and after ATC restart it reappears. It seems there is some CPU utilization when it disappears but it is hardly something that should make it dysfunctional. Note that even after the CPU usage goes down it still does not reconnect without ATC restart. Hope the fixes resolve this issue as well - @vito is there ETA for these fixes?

**Comment by databus23** [comment]
I'm wondering if "my" issue https://github.com/concourse/concourse/issues/750 is about the same problem.

What I'm seeing is that the workers stop heartbeating but the tcp connections to the TSA are left open. Restarting the worker always fixes the problem for me. That restarting the ATC/TSA also helps could  be explained that by closing the connection server side the workers are finally forced to reconnect.

So I'm wondering if its actually a problem in the workers heartbeating logic. Maybe there is an edge case where it chokes on a bad connection. I tried briefly looking and the concourse-bin beacon code but couldn't figure out if it reconnects in all cases when the heartbeat timeout expires.

**Comment by databus23** [comment]
Ok seems like I had it backwards. Its the atc that is doing the actual heartbeating. The worker is sending keep alive beacons. I confused the two. The general observation I have is the same. I have an established tcp connection between tsa and worker where no packets are send in either direction anymore.

**Comment by freelock** [comment]
Ok, so it looks like the ATC hung an hour ago:

![selection_518](https://cloud.githubusercontent.com/assets/46937/20196785/26d6072a-a751-11e6-93b9-52ecd9ba4c79.png)

![selection_519](https://cloud.githubusercontent.com/assets/46937/20196810/36b24370-a751-11e6-887d-a70a7479a89d.png)

fly workers is showing my tagged worker, but not my untagged worker. 3 builds are showing as errored, 1 as pending, failing with "No workers satisfied: resource type 'pool'"

The untagged worker's last log lines:

```
Nov 10 12:56:11 worker07.freelock.com concourse[2537]: {"timestamp":"1478811371.130336046","source":"baggageclaim","message":"baggageclaim.tick.reaping","log_level":1,"data":{"handle":"e3d1d03c-2795-42e1-7fe3-6a094786bcab","session":"25878","ttl":300}}
Nov 10 12:56:11 worker07.freelock.com concourse[2537]: {"timestamp":"1478811371.164362192","source":"baggageclaim","message":"baggageclaim.repository.destroy-volume.destroyed","log_level":1,"data":{"session":"3.1926862","volume":"e3d1d03c-2795-42e1-7fe3-6a094786bcab"}}
```

The tagged worker is still logging:

```
Nov 10 14:28:49 Freelock-06 concourse[26521]: {"timestamp":"1478816929.233577967","source":"guardian","message":"guardian.list-containers.starting","log_level":1,"data":{"session":"34634"}}
Nov 10 14:28:49 Freelock-06 concourse[26521]: {"timestamp":"1478816929.234014988","source":"guardian","message":"guardian.list-containers.finished","log_level":1,"data":{"session":"34634"}}
Nov 10 14:28:49 Freelock-06 concourse[26521]: {"timestamp":"1478816929.399945736","source":"guardian","message":"guardian.api.garden-server.get-properties.got-properties","log_level":1,"data":{"handle":"f6ab3167-3e03-4078-53f0-435832632d28","session":"2.1.114159"}}
```

On the ATC side, seeing lots of getsockopt errors around the time things started failling:

```
Nov 10 12:40:33 hector concourse[2376]: {"timestamp":"1478810433.841525316","source":"atc","message":"atc.syncer.lindberg
h:scheduler.tick.scheduling.try-start-next-pending-build.do.get.retry-round-tripper.retrying","log_level":1,"data":{"buil
d-id":6312,"build-name":"21","error":"dial tcp 127.0.0.1:33474: getsockopt: connection refused","failed-attempts":230,"na
me":"drushrc","ran-for":"1h0m15.353720705s","session":"13.76.75.3.22.4.15.36"}}
Nov 10 12:40:33 hector concourse[2376]: {"timestamp":"1478810433.841995239","source":"atc","message":"atc.syncer.lindberg
h:scheduler.tick.scheduling.try-start-next-pending-build.do.get.continuous-heartbeat.tick.failed-to-get-volume-size","log
_level":2,"data":{"build-id":6312,"build-name":"21","error":"Get http://127.0.0.1:33474/volumes/0279a9c3-322a-4a21-6b01-6
f1463e86a2b/stats: dial tcp 127.0.0.1:33474: getsockopt: connection refused","name":"drushrc","session":"13.76.75.3.22.4.
15.2.13","volume":"0279a9c3-322a-4a21-6b01-6f1463e86a2b"}}
```

... but actually I'm seeing these all day, even when things were going smoothly.

Anything in particular I should be looking for?

**Comment by charlieoleary** [comment]
@freelock Do you happen to have any info about load on the workers and/or ATC before and after it dropped?

**Comment by freelock** [comment]
@charlieoleary here's 1M load...
![selection_520](https://cloud.githubusercontent.com/assets/46937/20199816/10416ce6-a762-11e6-904a-82ed5889152f.png)

... Blue line is the untagged worker, green is the ATC. Our untagged worker always ends up under high loads when we have a handful of pipelines enabled... given that we have > 50 pipelines, we keep them paused when not in use...

**Comment by freelock** [comment]
Another worker fail. And the ATC is broken too...

```
john@Freelock-04 >git/pipelines (master)> fly -t freelock check-resource -r seattlehumane/pipelines
error: Unexpected Response
Status: 500 Internal Server Error
Body:

```

:sob:

**Comment by freelock** [comment]
ok, this time restarting only the untagged worker got it working again... the 500 error must be because there were no workers that could do the check resource.

**Comment by freelock** [comment]
... but no jobs actually are getting started anymore, ones that were already running have now spent > 30 minutes waiting for a pool resource, while the resource itself has unclaimed locks, and newly triggered jobs are waiting on suitable versions... and the number of TCP connections to the atc have jumped up again and nothing whatsoever seems to be happening.

This has happened 3 times in the past day.

**Comment by ggeorgiev** [comment]
just as input - I had a static code analysis tool that was running 16 threads on 8 core workers. After I limited it to 5 threads I haven't seen the disconnection for a while.

These though for me is still a bug - after all those are workers - temporary CPU starvation should not be so critical.

**Comment by freelock** [comment]
Since upgrading to 2.5.0, we've seen this behavior a lot less often, but we still just triggered it. Our untagged worker got up around 166 containers, and a load over 50, and then it disappeared from fly workers and jobs started failing. We're in the midst of our heavy-load period, when we're pushing Concourse hard -- but until now Concourse has been running smoothly since we upgraded to 2.5.0, about 3 weeks ago...

**Comment by vito** [comment]
I wonder if this is related to #750 since you mentioned workers dropping off? We've investigated that issue pretty thoroughly and have a theory as to the root cause. If the theory is true it'd happen more for workers that have large payloads streamed to/from them, as there's a 1GB threshold after which `crypto/ssh` forces a key exchange, which can deadlock.

Also #629 may improve this a bit.

**Comment by freelock** [comment]
Hi,

Hmm, well, I think the only resource that is over 1GB is the docker image used for the task that is failing most often. However, this image is almost never updated, and it runs fine if there are only 1 - 3 active jobs.

We seem to be having problems when there are more jobs running than that. When we're rolling out updates, it's common for us to have 10 - 12 pipelines active, each with 1 or 2 active jobs -- this is when Concourse locks up on us and having trouble. And the trouble starts with far fewer active jobs than that -- anytime there's 5 or 6 active jobs we're crossing our fingers that they will complete and not wedge the system. (And we currently have > 45 pipelines in all...)

I was thinking of working around this by having our chat bot queue up jobs and feed them to concourse one at a time -- Concourse itself can't seem to handle that much going on without having trouble... We did this with our nightly environment check job, and that has run flawlessly across 31 pipelines every night for the past 7 weeks.

#629 I think might be a huge help here.

**Comment by vito** [comment]
@freelock To clarify, it's 1GB of transfer, *ever*, over time. So it could also be that you streamed smaller resources, but frequently enough to hit that threshold. This also includes things like build logs being streamed from the worker, plus heartbeating - literally all network traffic. IaaS network metrics could help show this.

**Comment by vito** [comment]
It's also possible that the deadlock doesn't occur if there's not much else going on, as it may only happen when a (pretty small) internal buffer is full. That could explain why feeding one job at a time works better.

**Comment by vito** [comment]
Consolidating this into https://github.com/concourse/concourse/issues/844 as it's getting hard to track these many similar-sounding issues. Leaving #750 open as it's a smaller facet that we've already independently debugged, even though it may relate to this.

**Comment by freelock** [comment]
Ah, ok, I'm sure there's > 1GB getting transferred when we're pushing a bunch of jobs through. Our typical main git project in each pipeline is 150M - 300M all by itself -- 4 or 5 of those will hit 1GB pretty easily, before we get to the other resources... And each pipeline currently has ~20 resources (though most of those should be cached and rarely change -- only the individual project resource and the generated artifacts would churn regularly).
