### ISSUE TITLE
Validate Pipeline doesn't recognize IDToken Var Source

### ISSUE THREAD

**Issue by kcbimonte** [concourse/concourse#9310]
### Summary

When trying to validate a pipeline containing idtoken var source using fly validate-pipeline, the command reports a validation error:

### Steps to Reproduce

1. Log into a Concourse instance running at least 7.14.0
2. Create a sample pipeline using the var_source `idtoken`
3. Run `fly vp -c pipeline.yml` against your sample pipeline
4. Observe the invalid configuration error

### Expected Results

I expected to see a message similar to no issues found when running the validate command with an IDToken var source.

### Actual Results

When I ran the validate pipeline (`fly -t main vp -c pipeline.yml`) against the following pipeline:

```yaml
var_sources:
  - name: idtoken
    type: idtoken
    config:
      subject_scope: pipeline
      audience: ["sts.amazonaws.com"]
      expires_in: 1h

jobs:
  - name: print-credentials
    plan:
      - task: print
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: ubuntu}
          params:
            ID_TOKEN: ((idtoken:token))
          run:
            path: bash
            args:
              - -c
              - |
                echo "token: $ID_TOKEN"
                // or
                echo "token: ((idtoken:token))"
                // Send this token as part of an API-Request to an external service
```

I received the following error:

```shell
WARNING:
Error loading existing config:
  - invalid variable sources:
        unknown credential manager type: idtoken


error: configuration invalid
```

### Web Node(s) configuration

Using the quickstart docker compose, I have the following configuration:

```yaml
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      # instead of relying on the default "detect"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: tutorial
      CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"
      # For ARM-based machine, change the Concourse runtime to "houdini"
      CONCOURSE_WORKER_RUNTIME: "containerd"
      CONCOURSE_ENABLE_PIPELINE_INSTANCES: true
      CONCOURSE_ENABLE_ACROSS_STEP: tru
```

### Concourse Version

7.14.1

### Did this use to work?

No

**Comment by kcbimonte** [comment]
Some additional context. This may have been an issue (#5356) in the past and was resolved by dynamically registering all the var_sources (#5357).

Recommending that if this is the fix, dynamically registering the idtoken var source `validate_pipeline.go` file and adding additional tests to cover the new var_source.

cc: @dbaumgarten this may interest you as well.

**Comment by dbaumgarten** [comment]
Yeah, it really seems like I forgot to register the new var_source in fly. (Honestly, I didn't even know that validate-pipeline command exists)

Should be an easy fix. I will try to open a PR for this in the next few days.

**Comment by kcbimonte** [comment]
Thanks! And it's definitely a useful CLI command when you're building out pipelines since it checks format and some keys before trying to apply to an actual Concourse instance.

**Comment by dbaumgarten** [comment]
PR is open. Please check. 👍

**Comment by dbaumgarten** [comment]
The PR-pipeline seems to fail for my PR. However I still can't see the build-logs. I guess I am missing the required permissions? What do I need to do to get these?

**Comment by kcbimonte** [comment]
@taylorsilva can you help here with permissions?

**Comment by taylorsilva** [comment]
@dbaumgarten I invited you to the `all` team in the Concourse org that will give you permissions to see PR build logs in ci.concourse-ci.org

**Comment by dbaumgarten** [comment]
Thanks, that worked, I can see the build logs now.

The integration-tests are failing for the PR. But as far as I can tell the failure has nothing to do with my changes.
Is the pipeline generally broken right now?

**Comment by taylorsilva** [comment]
Just looked and it's the same logs/error I saw that resulted in me making this commit: https://github.com/concourse/concourse/commit/2feec953cdbd554152594b6b4fe03f9f63885096

Which the PR would get. Going to invalidate the cache for the resource and try running the check again.

**Comment by domgoodwin** [comment]
Is this going to be added to a new released version of Concourse/fly? I can see releases came out recently but didn't include this change

**Comment by taylorsilva** [comment]
Yes, there's a planned v8 coming out that'll include this.
